### ISSUE TITLE
Please replace non-free color space profile with free one

### ISSUE THREAD

**Issue by apoleon** [torakiki/sambox#76]
Currently sambox distributes a non-free color space profile from Hewlett-Packard. The license does not allow modification.

https://github.com/torakiki/sambox/blob/master/src/test/resources/org/sejda/sambox/pdmodel/sRGB%20Color%20Space%20Profile.icm.LICENSE.txt

Please consider to replace the file with a free alternative. PDFBox 2.0.6 ships some zlib licensed profiles which should be a good replacement.

**Comment by torakiki** [comment]
Yes, this is the related issue https://issues.apache.org/jira/browse/PDFBOX-3571
We are usually in line with PDFBox, this was probably overlooked.
