### ISSUE TITLE
Handle invalid header

### ISSUE THREAD

**Issue by fostersimonj** [torakiki/sambox#78]
Came across a PDF header with

```
2 J
%PDF-1.7
3 0 obj
```

Acrobat Reader and other libraries (eg poppler pdfinfo, Apache tika) handle this, but Sambox fails  [here](https://github.com/torakiki/sambox/blob/master/src/main/java/org/sejda/sambox/input/PDFParser.java#L173-L177) since the first character on the first line is a digit

```
Caused by: java.io.IOException: Unable to find expected file header
	at org.sejda.sambox.input.PDFParser.readHeader(PDFParser.java:176)
```

**Comment by torakiki** [comment]
fixed and released
